
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-manager-app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    depends_on:
      - mailpit

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP
